<?php
require __DIR__.'/../../config/bootstrap.php';
use Pharmacy\Auth\Authorization;use Pharmacy\Support\Csrf;use Pharmacy\Inventory\StockLedgerService;use Pharmacy\Inventory\AdjustmentService;
Authorization::requireRole('ADMIN','INVENTORY');$message=$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){try{Csrf::validate((string)($_POST['csrf']??''));$id=(new AdjustmentService($pdo,new StockLedgerService($pdo)))->post((string)$_POST['type'],(int)$_POST['batch_id'],(float)$_POST['quantity'],trim((string)$_POST['reason']),(int)$_SESSION['user']['id']);$message="Adjustment #{$id} posted.";}catch(Throwable $e){$error=$e->getMessage();}}
$batches=$pdo->query("SELECT b.id,m.name,b.batch_no,b.expiry_date,b.quantity_available FROM medicine_batches b JOIN medicines m ON m.id=b.medicine_id WHERE b.quantity_available>0 ORDER BY m.name,b.expiry_date")->fetchAll();$recent=$pdo->query("SELECT a.*,m.name medicine,b.batch_no,u.full_name user_name FROM stock_adjustments a JOIN medicine_batches b ON b.id=a.batch_id JOIN medicines m ON m.id=b.medicine_id JOIN users u ON u.id=a.created_by ORDER BY a.id DESC LIMIT 50")->fetchAll();$title='Stock Adjustments';require __DIR__.'/../../templates/header.php';?>
<h2 class="page-title">Stock Adjustments / Write-off</h2><?php if($message):?><div data-flash="<?=htmlspecialchars($message)?>"></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error)?></div><?php endif;?>
<div class="card mb-4"><div class="card-body"><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?=htmlspecialchars(Csrf::token())?>"><div class="col-md-4"><label class="form-label">Batch</label><select class="form-select" name="batch_id" required><option value="">Select</option><?php foreach($batches as $b):?><option value="<?=$b['id']?>"><?=htmlspecialchars($b['name'].' | '.$b['batch_no'].' | Exp '.$b['expiry_date'].' | Qty '.$b['quantity_available'])?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="form-label">Type</label><select class="form-select" name="type" required><option>DAMAGE</option><option>EXPIRED</option><option>SUPPLIER_RETURN</option><option>ADJUSTMENT_OUT</option><option>ADJUSTMENT_IN</option></select></div><div class="col-md-2"><label class="form-label">Quantity</label><input class="form-control" type="number" step="0.001" min="0.001" name="quantity" required></div><div class="col-md-3"><label class="form-label">Reason</label><input class="form-control" name="reason" required></div><div class="col-md-1 d-flex align-items-end"><button class="btn btn-dark" data-confirm="Post this stock adjustment?">Post</button></div></form></div></div>
<div class="card"><div class="card-body"><table class="table datatable"><thead><tr><th>No.</th><th>Type</th><th>Medicine</th><th>Batch</th><th>Qty</th><th>Reason</th><th>User</th><th>Status</th></tr></thead><tbody><?php foreach($recent as $r):?><tr><td><?=htmlspecialchars($r['adjustment_no'])?></td><td><?=$r['adjustment_type']?></td><td><?=htmlspecialchars($r['medicine'])?></td><td><?=htmlspecialchars($r['batch_no'])?></td><td><?=number_format((float)$r['quantity'],3)?></td><td><?=htmlspecialchars($r['reason'])?></td><td><?=htmlspecialchars($r['user_name'])?></td><td><?=$r['status']?></td></tr><?php endforeach;?></tbody></table></div></div><?php require __DIR__.'/../../templates/footer.php';
