<?php
require __DIR__.'/../../config/bootstrap.php';
use Pharmacy\Auth\Authorization;use Pharmacy\Employees\EmployeeRepository;use Pharmacy\Employees\EmployeeImportService;use Pharmacy\Support\Csrf;
Authorization::requireRole('ADMIN','PHARMACIST');
$repo=new EmployeeRepository($pdo);$message=null;$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{Csrf::validate((string)($_POST['csrf']??''));
  if(isset($_FILES['csv'])&&$_FILES['csv']['error']===UPLOAD_ERR_OK){Authorization::requireRole('ADMIN');$svc=new EmployeeImportService($pdo,$repo);$r=$svc->importCsv($_FILES['csv']['tmp_name'],(int)$_SESSION['user']['id']);$message="Import: {$r['inserted']} inserted, {$r['updated']} updated, {$r['rejected']} rejected.";}
  else{Authorization::requireRole('ADMIN');$repo->save(['employee_code'=>trim($_POST['employee_code']??''),'name'=>trim($_POST['name']??''),'division'=>trim($_POST['division']??''),'department'=>trim($_POST['department']??''),'designation'=>trim($_POST['designation']??''),'phone'=>trim($_POST['phone']??''),'active'=>1]);$message='Employee saved.';}
 }catch(Throwable $e){$error=$e->getMessage();}
}
$q=trim($_GET['q']??'');$rows=$repo->search($q,100);$title='Employees';require __DIR__.'/../../templates/header.php';?>
<h2 class="page-title">Employees</h2><?php if($message):?><div data-flash="<?=htmlspecialchars($message)?>"></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error)?></div><?php endif;?>
<div class="row g-3"><div class="col-lg-4"><?php if(Authorization::hasRole('ADMIN')):?><div class="card"><div class="card-body"><h5>Add Employee</h5><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars(Csrf::token())?>"><?php foreach(['employee_code'=>'Employee ID','name'=>'Name','division'=>'Division','department'=>'Department','designation'=>'Designation','phone'=>'Phone'] as $n=>$l):?><div class="mb-2"><label class="form-label"><?=$l?></label><input class="form-control" name="<?=$n?>" <?=$n==='employee_code'||$n==='name'?'required':''?>></div><?php endforeach;?><button class="btn btn-dark">Save</button></form><hr><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=htmlspecialchars(Csrf::token())?>"><label class="form-label">CSV Import</label><input class="form-control mb-2" type="file" name="csv" accept=".csv" required><button class="btn btn-outline-dark">Import</button></form></div></div><?php endif;?></div><div class="col-lg-8"><form class="mb-2"><input class="form-control" name="q" value="<?=htmlspecialchars($q)?>" placeholder="Search employee ID or name"></form><div class="card"><div class="card-body"><table class="table datatable"><thead><tr><th>ID</th><th>Name</th><th>Division</th><th>Department</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=htmlspecialchars($r['employee_code'])?></td><td><?=htmlspecialchars($r['name'])?></td><td><?=htmlspecialchars($r['division']??'')?></td><td><?=htmlspecialchars($r['department']??'')?></td><td><?=$r['active']?'Active':'Inactive'?></td></tr><?php endforeach;?></tbody></table></div></div></div></div><?php require __DIR__.'/../../templates/footer.php';
