<?php
require __DIR__.'/../../config/bootstrap.php';
use Pharmacy\Auth\Authorization;use Pharmacy\Support\Csrf;use Pharmacy\Inventory\StockLedgerService;use Pharmacy\Inventory\FefoAllocator;use Pharmacy\Dispensing\DispenseService;
Authorization::requireRole('ADMIN','PHARMACIST');$message=$error=null;$rxId=(int)($_GET['prescription_id']??$_POST['prescription_id']??0);$rx=null;$rxItems=[];
if($rxId){$s=$pdo->prepare("SELECT p.*,COALESCE(e.name,x.name) patient_name,COALESCE(e.employee_code,x.patient_code) patient_code,d.name doctor FROM prescriptions p LEFT JOIN employees e ON e.id=p.employee_id LEFT JOIN external_patients x ON x.id=p.external_patient_id JOIN doctors d ON d.id=p.doctor_id WHERE p.id=:id AND p.status IN('OPEN','PARTIALLY_DISPENSED')");$s->execute(['id'=>$rxId]);$rx=$s->fetch();if($rx){$si=$pdo->prepare('SELECT pi.*,m.name medicine_name,m.strength FROM prescription_items pi JOIN medicines m ON m.id=pi.medicine_id WHERE pi.prescription_id=:id AND pi.quantity_dispensed<pi.quantity_prescribed');$si->execute(['id'=>$rxId]);$rxItems=$si->fetchAll();}}
if($_SERVER['REQUEST_METHOD']==='POST'){try{Csrf::validate((string)($_POST['csrf']??''));$items=[];foreach($_POST['medicine_id']??[] as $i=>$mid){if(!(int)$mid)continue;$items[]=['medicine_id'=>(int)$mid,'quantity'=>(float)($_POST['quantity'][$i]??0),'dosage_instruction'=>trim($_POST['dosage_instruction'][$i]??''),'prescription_item_id'=>($_POST['prescription_item_id'][$i]??'')!==''?(int)$_POST['prescription_item_id'][$i]:null];}$type=$_POST['patient_type']??'EMPLOYEE';$command=['patient_type'=>$type,'employee_id'=>$type==='EMPLOYEE'?(int)($_POST['patient_id']??0):null,'external_patient_id'=>$type==='EXTERNAL'?(int)($_POST['patient_id']??0):null,'prescription_id'=>$rxId?:null,'remarks'=>trim($_POST['remarks']??''),'items'=>$items];$id=(new DispenseService($pdo,new StockLedgerService($pdo),new FefoAllocator()))->post($command,(int)$_SESSION['user']['id']);$message="Dispense #{$id} posted successfully.";$rxId=0;$rx=null;$rxItems=[];}catch(Throwable $e){$error=$e->getMessage();}}
$employees=$pdo->query("SELECT id,employee_code,name FROM employees WHERE active=1 ORDER BY name LIMIT 1000")->fetchAll();$patients=$pdo->query("SELECT id,patient_code,name FROM external_patients WHERE active=1 ORDER BY name LIMIT 1000")->fetchAll();$medicines=$pdo->query("SELECT m.id,m.name,m.strength,COALESCE(SUM(CASE WHEN b.expiry_date>=CURDATE() AND b.status='ACTIVE' THEN b.quantity_available ELSE 0 END),0) stock FROM medicines m LEFT JOIN medicine_batches b ON b.medicine_id=m.id WHERE m.active=1 GROUP BY m.id ORDER BY m.name")->fetchAll();$recent=$pdo->query("SELECT d.id,d.dispense_no,d.dispense_at,d.patient_type,COALESCE(e.employee_code,x.patient_code) patient_code,COALESCE(e.name,x.name) patient_name,SUM(di.total_cost) value FROM dispenses d JOIN dispense_items di ON di.dispense_id=d.id LEFT JOIN employees e ON e.id=d.employee_id LEFT JOIN external_patients x ON x.id=d.external_patient_id WHERE d.status='POSTED' GROUP BY d.id ORDER BY d.id DESC LIMIT 30")->fetchAll();$title='Dispensing';require __DIR__.'/../../templates/header.php';?>
<h2 class="page-title">Dispense Medicines</h2><?php if($message):?><div data-flash="<?=htmlspecialchars($message)?>"></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error)?></div><?php endif;?>
<?php if($rx):?><div class="alert alert-info"><strong>Prescription <?=htmlspecialchars($rx['prescription_no'])?></strong> — <?=htmlspecialchars($rx['patient_code'].' - '.$rx['patient_name'])?> — Dr. <?=htmlspecialchars($rx['doctor'])?></div><?php endif;?>
<div class="card mb-4"><div class="card-body"><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars(Csrf::token())?>"><input type="hidden" name="prescription_id" value="<?=$rxId?>">
<?php if($rx):?><input type="hidden" name="patient_type" value="<?=$rx['patient_type']?>"><input type="hidden" name="patient_id" value="<?=$rx['patient_type']==='EMPLOYEE'?$rx['employee_id']:$rx['external_patient_id']?>"><?php else:?><div class="row g-2 mb-3"><div class="col-md-2"><label class="form-label">Patient Type</label><select class="form-select" name="patient_type" id="dPatientType"><option value="EMPLOYEE">Employee</option><option value="EXTERNAL">External</option></select></div><div class="col-md-6"><label class="form-label">Patient</label><select class="form-select" name="patient_id" id="dEmployee" required><option value="">Select employee</option><?php foreach($employees as $e):?><option value="<?=$e['id']?>"><?=htmlspecialchars($e['employee_code'].' - '.$e['name'])?></option><?php endforeach;?></select><select class="form-select d-none" id="dExternal"><option value="">Select external patient</option><?php foreach($patients as $p):?><option value="<?=$p['id']?>"><?=htmlspecialchars($p['patient_code'].' - '.$p['name'])?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Remarks</label><input class="form-control" name="remarks" placeholder="Direct issue / notes"></div></div><?php endif;?>
<div class="table-responsive"><table class="table" id="dispenseItems"><thead><tr><th>Medicine</th><th>Valid Stock</th><th>Qty to Dispense</th><th>Dosage</th><th></th></tr></thead><tbody>
<?php if($rxItems): foreach($rxItems as $it):$remaining=(float)$it['quantity_prescribed']-(float)$it['quantity_dispensed'];?><tr class="disp-row"><td><input type="hidden" name="medicine_id[]" value="<?=$it['medicine_id']?>"><input type="hidden" name="prescription_item_id[]" value="<?=$it['id']?>"><strong><?=htmlspecialchars($it['medicine_name'].' '.$it['strength'])?></strong><div class="small text-muted">Prescribed <?=number_format((float)$it['quantity_prescribed'],2)?> · Already <?=number_format((float)$it['quantity_dispensed'],2)?></div></td><td>FEFO validated on post</td><td><input class="form-control" type="number" step="0.001" min="0.001" max="<?=$remaining?>" name="quantity[]" value="<?=$remaining?>" required></td><td><input class="form-control" name="dosage_instruction[]" value="<?=htmlspecialchars($it['dosage_instruction']??'')?>"></td><td></td></tr><?php endforeach; else:?><tr class="disp-row"><td><select class="form-select medicine-select" name="medicine_id[]" required><option value="">Select medicine</option><?php foreach($medicines as $m):?><option value="<?=$m['id']?>" data-stock="<?=$m['stock']?>"><?=htmlspecialchars($m['name'].' '.$m['strength'])?></option><?php endforeach;?></select><input type="hidden" name="prescription_item_id[]" value=""></td><td class="stock-cell">0</td><td><input class="form-control" type="number" step="0.001" min="0.001" name="quantity[]" required></td><td><input class="form-control" name="dosage_instruction[]"></td><td><button type="button" class="btn btn-sm btn-outline-danger remove-disp">×</button></td></tr><?php endif;?>
</tbody></table></div><?php if(!$rx):?><button type="button" class="btn btn-outline-secondary" id="addDisp">Add Medicine</button><?php endif;?> <button class="btn btn-dark" data-confirm="Confirm dispensing and deduct stock?">Dispense</button></form></div></div>
<div class="card"><div class="card-body"><h5>Recent Dispensing</h5><table class="table datatable"><thead><tr><th>No.</th><th>Date</th><th>Patient</th><th>Type</th><th>Cost</th></tr></thead><tbody><?php foreach($recent as $r):?><tr><td><?=htmlspecialchars($r['dispense_no'])?></td><td><?=htmlspecialchars($r['dispense_at'])?></td><td><?=htmlspecialchars($r['patient_code'].' - '.$r['patient_name'])?></td><td><?=$r['patient_type']?></td><td>₹<?=number_format((float)$r['value'],2)?></td></tr><?php endforeach;?></tbody></table></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const t=document.querySelector('#dPatientType');if(t){const e=document.querySelector('#dEmployee'),x=document.querySelector('#dExternal');t.onchange=()=>{const ex=t.value==='EXTERNAL';e.classList.toggle('d-none',ex);x.classList.toggle('d-none',!ex);e.name=ex?'':'patient_id';x.name=ex?'patient_id':''}}const body=document.querySelector('#dispenseItems tbody');body.addEventListener('change',ev=>{if(ev.target.classList.contains('medicine-select'))ev.target.closest('tr').querySelector('.stock-cell').textContent=Number(ev.target.selectedOptions[0]?.dataset.stock||0).toFixed(2)});const add=document.querySelector('#addDisp');if(add)add.onclick=()=>{const r=body.querySelector('.disp-row').cloneNode(true);r.querySelectorAll('input').forEach(i=>{if(i.type!=='hidden')i.value=''});r.querySelector('select').value='';r.querySelector('.stock-cell').textContent='0';body.appendChild(r)};body.addEventListener('click',ev=>{if(ev.target.classList.contains('remove-disp')&&body.children.length>1)ev.target.closest('tr').remove()})});</script>
<?php require __DIR__.'/../../templates/footer.php';
