<?php
require __DIR__.'/../../config/bootstrap.php';
use Pharmacy\Auth\Authorization;use Pharmacy\Support\Csrf;use Pharmacy\Inventory\StockLedgerService;use Pharmacy\Inventory\ReceiptService;
Authorization::requireRole('ADMIN','INVENTORY');$message=$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{Csrf::validate((string)($_POST['csrf']??''));$pdo->beginTransaction();
  $receiptNo='RCV-'.date('YmdHis').'-'.random_int(100,999);$h=$pdo->prepare("INSERT INTO stock_receipts(receipt_no,supplier_id,supplier_invoice_no,invoice_date,receipt_date,status,remarks,created_by) VALUES(:no,:supplier,:invoice,:invoice_date,:receipt_date,'DRAFT',:remarks,:user)");$h->execute(['no'=>$receiptNo,'supplier'=>(int)$_POST['supplier_id'],'invoice'=>trim($_POST['supplier_invoice_no']),'invoice_date'=>$_POST['invoice_date'],'receipt_date'=>$_POST['receipt_date'],'remarks'=>trim($_POST['remarks']??''),'user'=>(int)$_SESSION['user']['id']]);$receiptId=(int)$pdo->lastInsertId();
  $line=$pdo->prepare('INSERT INTO stock_receipt_items(receipt_id,medicine_id,batch_no,manufacture_date,expiry_date,received_quantity,free_quantity,purchase_rate,tax_rate,line_value) VALUES(:receipt,:medicine,:batch,:mfg,:expiry,:qty,:free,:rate,:tax,:value)');
  foreach($_POST['medicine_id']??[] as $i=>$medicineId){if(!(int)$medicineId)continue;$qty=(float)($_POST['received_quantity'][$i]??0);$free=(float)($_POST['free_quantity'][$i]??0);$rate=(float)($_POST['purchase_rate'][$i]??0);$tax=(float)($_POST['tax_rate'][$i]??0);$value=round($qty*$rate*(1+$tax/100),2);$line->execute(['receipt'=>$receiptId,'medicine'=>(int)$medicineId,'batch'=>trim($_POST['batch_no'][$i]??''),'mfg'=>($_POST['manufacture_date'][$i]??'')?:null,'expiry'=>$_POST['expiry_date'][$i]??'','qty'=>$qty,'free'=>$free,'rate'=>$rate,'tax'=>$tax,'value'=>$value]);}
  $pdo->commit();(new ReceiptService($pdo,new StockLedgerService($pdo)))->post($receiptId,(int)$_SESSION['user']['id']);$message="Receipt {$receiptNo} posted.";
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}
}
$suppliers=$pdo->query('SELECT id,name FROM suppliers WHERE active=1 ORDER BY name')->fetchAll();$medicines=$pdo->query('SELECT id,medicine_code,name,strength FROM medicines WHERE active=1 ORDER BY name')->fetchAll();$recent=$pdo->query("SELECT r.receipt_no,r.receipt_date,r.supplier_invoice_no,s.name supplier,r.status FROM stock_receipts r JOIN suppliers s ON s.id=r.supplier_id ORDER BY r.id DESC LIMIT 50")->fetchAll();$title='Stock Receipts';require __DIR__.'/../../templates/header.php';?>
<h2 class="page-title">Stock Receipt</h2><?php if($message):?><div data-flash="<?=htmlspecialchars($message)?>"></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error)?></div><?php endif;?>
<div class="card mb-4"><div class="card-body"><form method="post" id="receiptForm"><input type="hidden" name="csrf" value="<?=htmlspecialchars(Csrf::token())?>"><div class="row g-2 mb-3"><div class="col-md-4"><label class="form-label">Supplier</label><select class="form-select" name="supplier_id" required><option value="">Select</option><?php foreach($suppliers as $s):?><option value="<?=$s['id']?>"><?=htmlspecialchars($s['name'])?></option><?php endforeach;?></select></div><div class="col-md-3"><label class="form-label">Supplier Invoice</label><input class="form-control" name="supplier_invoice_no" required></div><div class="col-md-2"><label class="form-label">Invoice Date</label><input class="form-control" type="date" name="invoice_date" value="<?=date('Y-m-d')?>" required></div><div class="col-md-2"><label class="form-label">Receipt Date</label><input class="form-control" type="date" name="receipt_date" value="<?=date('Y-m-d')?>" required></div></div>
<div class="table-responsive"><table class="table" id="receiptItems"><thead><tr><th>Medicine</th><th>Batch</th><th>Mfg</th><th>Expiry</th><th>Qty</th><th>Free</th><th>Rate</th><th>Tax %</th><th></th></tr></thead><tbody><tr class="item-row"><td><select class="form-select" name="medicine_id[]" required><option value="">Select</option><?php foreach($medicines as $m):?><option value="<?=$m['id']?>"><?=htmlspecialchars($m['name'].' '.$m['strength'])?></option><?php endforeach;?></select></td><td><input class="form-control" name="batch_no[]" required></td><td><input class="form-control" type="date" name="manufacture_date[]"></td><td><input class="form-control" type="date" name="expiry_date[]" required></td><td><input class="form-control" type="number" step="0.001" min="0.001" name="received_quantity[]" required></td><td><input class="form-control" type="number" step="0.001" min="0" name="free_quantity[]" value="0"></td><td><input class="form-control" type="number" step="0.0001" min="0" name="purchase_rate[]" required></td><td><input class="form-control" type="number" step="0.01" min="0" name="tax_rate[]" value="0"></td><td><button class="btn btn-sm btn-outline-danger remove-row" type="button">×</button></td></tr></tbody></table></div><div class="d-flex gap-2"><button type="button" class="btn btn-outline-secondary" id="addRow">Add Medicine</button><button class="btn btn-dark" data-confirm="Post this stock receipt?">Post Receipt</button></div></form></div></div>
<div class="card"><div class="card-body"><h5>Recent Receipts</h5><table class="table datatable"><thead><tr><th>Receipt</th><th>Date</th><th>Supplier</th><th>Invoice</th><th>Status</th></tr></thead><tbody><?php foreach($recent as $r):?><tr><td><?=htmlspecialchars($r['receipt_no'])?></td><td><?=$r['receipt_date']?></td><td><?=htmlspecialchars($r['supplier'])?></td><td><?=htmlspecialchars($r['supplier_invoice_no'])?></td><td><?=$r['status']?></td></tr><?php endforeach;?></tbody></table></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const tbody=document.querySelector('#receiptItems tbody');document.querySelector('#addRow').onclick=()=>{const row=tbody.querySelector('.item-row').cloneNode(true);row.querySelectorAll('input').forEach(i=>{i.value=i.name.includes('free_quantity')||i.name.includes('tax_rate')?'0':''});row.querySelector('select').value='';tbody.appendChild(row)};tbody.addEventListener('click',e=>{if(e.target.classList.contains('remove-row')&&tbody.children.length>1)e.target.closest('tr').remove()})});</script>
<?php require __DIR__.'/../../templates/footer.php';
